---
title: "OneSDM: Automated Workflows for Species Distribution Modelling"
output: github_document
---

## Overview

To identify species likely to establish, spread and impose threats on native ecosystems in Europe, we will
develop workflows to dynamically model potential current and future species distributions of a range of
terrestrial IAS of Union and regional concern. The workflows will enable regular automatic updates of the
models and their respective predictions to make use of newly available data, including those generated in
T2.1–T2.4, and will build on the work currently performed in the projects BioDT and B3 (see Table 1.2.2.1).
We will review cutting-edge advances in modelling (such as Bayesian joint SDMs and integrated SDMs) and
will develop these within our workflows where they are practicable and likely to support effective data
integration and better model outputs (e.g. better propagation of model uncertainty for prioritisation and
impact assessments). We will project the potential future distributions and impacts of IAS to 2050 under four
recently developed scenarios of socio-economic development (Shared Socioeconomic Pathways) and climate
change (Representative Concentration Pathways)

<br/>

## Installation

You can install the development version of `OneSDM` from GitHub using the `remotes` package:

``` r
# Install remotes if not already installed
if (!require("remotes")) install.packages("remotes")

# Install OneSDM from GitHub
remotes::install_github("MarinaGolivets/OneSDM", dependencies = TRUE)
```

## Dependencies

The `OneSDM` package depends on several R packages for its functionality. Check the [`DESCRIPTION`](DESCRIPTION) file for a complete list of dependencies.

The <a href="https://github.com/elgabbas/ecokit" target="_blank">`ecokit`</a> package is one of the key dependencies used for ecological data handling and analysis. Make sure to install/update it before using `OneSDM`:

``` r
if (!require("ecokit")) remotes::install_github("elgabbas/ecokit", dependencies = TRUE)
# or update if already installed
remotes::update_packages("ecokit")
```

<br/>

## Contributing

`OneSDM` is an open-source project and still in development stage. We welcome contributions from the community! If you encounter issues, have suggestions, or want to add new features, please:

- **Report issues** or suggest features on the [GitHub issue tracker](https://github.com/MarinaGolivets/OneSDM/issues).
- **Submit pull requests** with bug fixes or enhancements via the [GitHub repository](https://github.com/MarinaGolivets/OneSDM).
- **Contact us** directly at `elgabbas[at]outlook[dot]com` or `marina.golivets[at]ufz[dot]de` for collaboration ideas or questions.
